language: node_js
env:
  global:
  - TEST_LOC="sauce"
  - GOOGLE_CLIENT_ID=""
  - GOOGLE_CLIENT_SECRET=""
  - REDISCLOUD_URL=""
  - BASE_URL=http://localhost:5000
  - SESSION_SECRET=not-so-secret-for-testing
  - USE_STANDALONE_PYRET=true
  - PYRET_RELEASE_BASE="https://s3.amazonaws.com/pyret-horizon/current"
  - PYRET="http://localhost:5000/js/cpo-main.jarr.gz.js"
  - CURRENT_PYRET_RELEASE=""
  - PORT=5000
  - SAUCE_TEST_TARGET="http://localhost:5000"
  - SAUCE_USERNAME="pyret-lang"
  - secure: e0vpQGmW0d69Ql72Mw6gsGsMxAKgt61ZNqsfQEtNlAGtx7CbTKe3xg8kF1ygwFVEB7GDmTaojTcSGbRwqqZ5GAa8dsTAkefhOtfCDV5KUjvXXbpo9J/8YLiZiIy7ksHyh1yhByvvWmZZpjmdxWwcH8gUqtpae3bGtz7rQX3jLf2v3OR5uVFt8vKRMSR9imCWmq6tpnu+GVoaCFOHjq3U7LS1h78R2LJz+MnTuCbDtYFlxp/sAyS7vSXssFScl6wqOsgH5PHlj+kaHhFWLhzsAzG1RoHftqqIeinXzDcYo8EC/c6O3hMf2KtHm/Hsh1dPR8GnE6WClxPw0xNbh10jVf7b1CXuzKGF8a1JlmtsVztiujsMswZGGLpTkqBvBAiuDsMOwKFNk7UrR5FA/0bVMMsluKxW/0UBzVPN9QyMKAs19ca1t/qT3abxYFyvXrDibKMLuS1uCCsZbwTkjkPwfWBzin8ohK2gLi+y24eQFSd27XWcmk+fJHfgJ458OgvczubK0CsyPAaJtCvRBYKvLQaEtkc4RkoM0yx6NhYYLCZqH1DRneam40rVSrVO41yT/PUnA5U64q16ptbn90Vgw/yKlp9OLtWKheBDTinwbst1kegbCSj4qZtORFLIQIUsZQN6SUm9tCACqFosDpRXAzURc2IOdsSUmtJEqvkijsc=
  - secure: m7Tuxlnl9PYxrk0twLy/5sHGFJ+EGi3qxqvlVpwa3PhUMg0ExcZPaTGjgOKrikiVIpKhdy7SIP8ZMQXgbnV7mnLVG3yvxLGW4LyKAfscLmbup1IWwA6RoPdwpPxFwxzzgG/WBDo5Wfs1SLVuE9eyX8BYiT+C1VX/qYPUPuj9bRNIVJkfmiLSpnefs8b5iCKlLtm2CpZv1aGr3ICIuISl7BbtTnu4mOCcjTq26Lgsfg/gf37o3j4XUnLJX4acIfkfMLkn9rCuUcZZj8k5R/CW2W8AHp1/j12LefMkysS0il91+yhGPummmr7eN8MMyEMx+4T9Jzch31sYSQrI5WdBF7UREXRTMyRcRh8ICIW9yu+PjwP2SllCi3ZYHdqQQocVJEvyzi/hE+moINOt+EQIlp0Bo73Ing0r6cXIHCcB1DyIiE2ptZj57PP2a4lJ5yFvDINqxmGGYSR0vdd4+F6a/rOOdzPIFtw180QfYEQhcbPranujOweGZdiD+nv1dutFglPVcgeoYJrHp3jafUKi479+kWrrsRBx3Qh70Jp5CL9/a1Md1rIjhCEaqKmQ6/l7ZWt1hi/KkkxhB8oprYQDoPdsUMZ5gvRxwWIAX7AD/cc478xIeRuBCjWXLGgk/GSL31wgz7kpiOLdq2J9XIzb2e1LWC2bR8aYEW+tP3D+tno=
  matrix:
  - SAUCE_BROWSER="chrome"
  - SAUCE_BROWSER="firefox"
#  - SAUCE_BROWSER="safari"
#  - SAUCE_BROWSER="ie"
node_js:
- 6.2.1
before_script:
- node src/run.js &
- sleep 3
addons:
  sauce_connect: true
script:
- mocha --harmony
- echo "Skipping tests"
install:
- npm install --ignore-scripts
- make web
- make deploy-cpo-main
deploy:
  provider: s3
  access_key_id: AKIAJGVNL7LGVGTQS4PA
  secret_access_key:
    secure: maJZXDR077NqqPA60MVn901PYgqpzEbKeMAshDiKWtrQGKd+UwdazMooTTO2VN+8kqwMsplb/GkhsIxTWGyH8Ib6+iXatJ2vtvtnXPvKY8J+oeZnkdXRnict/WTopOf2zLEjd0SmSS7MMEjdX7J7eJYpGrnUX+bcLwRZxvl+8gCUeel22S0skwnU7wAqpDLlpGoDJJEtyiaNGyOXjze59hC1ZPG9pcDQtN7GKClJtNenPoUIrutXC/LfU3fACkcirKh3P3xDHbZcGXp9yrofYRU+u4VHB790qxc5VqHFojD2ediix6jQBOWsQppvZjKIeHiBnXxydxajROIstaW/hGj7ERFqfM+NXpCvyVwuP5YWqIU/2zEQTrKXtLraHIC+Tl/l3CxJwaMfAgdI3fjcD3LJnD5j2C+32wK0UweC/T+fSeZSOkYJkqHjjcI0jHD8HaRIoCKl1lbzyWH4JaNJ5QeWKWPUgKYBIxNUIBO5kN/surXq6fRsMFAxra8TjqOSyvpgx6NZ6BlHcpGogsD0pC5OL89r+tdyip5AjEGF7wJM3Nt4210nKTKx93IxcrKQINewXFK9++7I8ava2+l233NDbWJqqtb9ADO13g/6RtRqU1WRks1klQf/AAIsnd1JSuUyNf2XbDL2Kmsiq1EuD/UOHvcfSIdkPuZZar3rtrg=
  bucket: pyret-sql
  local-dir: build/web/js
  upload-dir: sql
  acl: public_read
  skip_cleanup: true
  detect_encoding: true
  on:
    repo: brownplt/code.pyret.org
    branch: sql
