language: ruby
sudo: required
rvm:
  - 2.2
env:
  global:
  - TEST_LOC="sauce"
  - GOOGLE_CLIENT_ID=""
  - GOOGLE_CLIENT_SECRET=""
  - GOOGLE_CHROME_BINARY=/usr/bin/google-chrome-stable
  - secure: "TYqxrQOzkzQcyfDfLz9fOklDjK+vkXg0Jzp8wTynenz8ZzLIac6UKH3DZza7KcQAdgNhhSYoekh05z+b2/EaYKvo+SNDDsfWEP2qjBCL6GxccDE8Ti6itt4orGZUT2XKd6FkDbXDq9j3lUfKlG78lIImGiZKL1UN2WnQozXxBpdp1C8c4V2UcXo70u26Ii/m9eTYGoQfUvVa57lqpA7dMsuVW6lffTmGAcL0pY9penE6+tv1B7pxzQ7wrl+eQh4qw423qCJCWHRKKHVtPqvSafh6E8/wJIc5OUXRvy1Uz6eM4oX6PWfs0Knrznh1fLtFaJSXzSEaDNzJesoInvDINsQ8HqM9dYv95Codbg0wh9QlW3ZFg8OL8gAG2i9dScGRMqtTjz+cRpIDP1ppDaWypMrvLCoRVV/WfufQQTqZeESAFvOU4fcihlwAGaadEa2D4SVY72GXxIuxox2fKjNtxfCggoZhUZJQUWUP/C7x/W1qbu2XrgxGYB0VpCUcpFAH7Zsl2P96WBfIvjHvxITTCEA86lyV6ZcdX/fhCVEPGabBz5Et5hHbH1jFV3T3qDJpMLmeLbhZSHVsUrnnsb0qkEGX3jgHF6WaCDgwiEAzmGS4/JKsW5MlZvAdd2gd+EEowqMCA9gXRyR8RZr2OyxrKs73U7GyH/lgpHeZURf6YAY="
  - REDISCLOUD_URL=""
  - BASE_URL=http://localhost:5000
  - SESSION_SECRET=not-so-secret-for-testing
  - USE_STANDALONE_PYRET=true
  - PYRET="http://localhost:5000/js/cpo-main.jarr"
  - CURRENT_PYRET_RELEASE=""
  - PORT=5000
  - SAUCE_TEST_TARGET="http://localhost:5000"
  - SAUCE_USERNAME="pyret-lang"
  - secure: e0vpQGmW0d69Ql72Mw6gsGsMxAKgt61ZNqsfQEtNlAGtx7CbTKe3xg8kF1ygwFVEB7GDmTaojTcSGbRwqqZ5GAa8dsTAkefhOtfCDV5KUjvXXbpo9J/8YLiZiIy7ksHyh1yhByvvWmZZpjmdxWwcH8gUqtpae3bGtz7rQX3jLf2v3OR5uVFt8vKRMSR9imCWmq6tpnu+GVoaCFOHjq3U7LS1h78R2LJz+MnTuCbDtYFlxp/sAyS7vSXssFScl6wqOsgH5PHlj+kaHhFWLhzsAzG1RoHftqqIeinXzDcYo8EC/c6O3hMf2KtHm/Hsh1dPR8GnE6WClxPw0xNbh10jVf7b1CXuzKGF8a1JlmtsVztiujsMswZGGLpTkqBvBAiuDsMOwKFNk7UrR5FA/0bVMMsluKxW/0UBzVPN9QyMKAs19ca1t/qT3abxYFyvXrDibKMLuS1uCCsZbwTkjkPwfWBzin8ohK2gLi+y24eQFSd27XWcmk+fJHfgJ458OgvczubK0CsyPAaJtCvRBYKvLQaEtkc4RkoM0yx6NhYYLCZqH1DRneam40rVSrVO41yT/PUnA5U64q16ptbn90Vgw/yKlp9OLtWKheBDTinwbst1kegbCSj4qZtORFLIQIUsZQN6SUm9tCACqFosDpRXAzURc2IOdsSUmtJEqvkijsc=
  - secure: "E19TyEFE1iQSRrZI4w6ahWgFGEFZBiUgxn/Pqq5sQwHlMNpai+bVydDRVlcQ0NsrdPmyXY/4+29wMjsAHbSaiBuqgG5PbtpChJK7a+8583G6CrbkWdZgwkMDpqPQ2IBEWVYeybvl36wuXJ4HNCqImPODWvX1Wxzk5RCK/gM4PNu3OdmQm3+6O8y1N6r0Y/lnqeAxhaZ5wv01/6EE3I3rAbnFxnu0wIJ7AfNV64VRk+tqwYuM5fLXrl6yhelSwp9q5CLEwvvYknBkklHAXbvxc2qo8XfZb6Zb701NyGvFW86Acgo1dytqV+BNmxNj4FfnXj+rxi/SDpiKEifzj5UYLIAgAx/qbxWSHD8SHiOL1WMa7N3vN2Dh+O+9vCLDwtpzbC0kJqxVMei8buAR4pLReZO0OsmHGXDPApoqOdxvQ0Z2VtEWojIWaJSIl0gTaWKAPAE6GMT0zRQcmm6GPXmLpWGc/9MZKJ5lTXQloucRaStRhPYV4x2HNF4vVZmJ0RWQexAX4qsUiaVFs0jdnJTDvgyPWj+f7qJaaqNFfXz9TyP2N8LSjPdGBYfkWIbkv8dXjJCufXX29BbOD5Yq1NcRQxgTnQO1cvXs1/MJOrK8tCAQ/rZUqQakBMg71fhznOm2lejiiingfnq846C1v27KxZzFLnGIOfDUbMAgS1sbGUU="
  - secure: "W74n+StLe0w+Lm6KNQN3lLzj4BFCy7vVSRCOQ3t5e3uSXDyLubqgRTXTXPoeypzcztbnMsd8Y57FyjJEaUydb2LPATEoJ9VbBy0ohXV/c3bucJSa4ZJxvb/8L62cepsZkRmoMl1HpW2kLWle50UdCLRqE0aGNHwM9FXfBAd279vmjmvPhFtGEiKkDek/ckroebG0n0xAox56ZmnuJM4boG3o0oUNjSE4U4W/RKMoApLJlUcEcdmWzJvOILeNvydFrHzQcSeHx6uH5LJg/N6RCHb++MI+BiUrAeGa0jm0YXFH0mdDmjCACAcRUzlyAGuadb2dAPcgKPV7xGyDJIn6+OD9dhwEGTGzyKr622fUcCa5+t4PERBFq7nYj7BU1CoqWUsYN6jArkH0ye7lA9usNZsHNXoykZkhpJYEoygYQg6mGnO0v0sRiUbv0BFQ4tN+l/ejvLfCiczjhuBgHlm7m0TUsH94dzeHFqGPlNGy75Rq9PM+0kxvN/TLY3udymKzpTJlbcaDvwQ37unBU2h7DpAYzscxyMcPbHo/F2lnmK/vlpSAsSjkdnpVp4Av+urn8G2eVJw+XnLWCQb4GIRsFzLfXOAPdhcQIZHfhiQTUXgFl+ahC2hEdC1sjho0yWWOHIhRoQ/5sLenB4hFTozxhbIKZTlyWI7FwuPnpWnhvAY="
  matrix:
  - SAUCE_BROWSER="chrome"
#  - SAUCE_BROWSER="firefox"
#  - SAUCE_BROWSER="safari"
#  - SAUCE_BROWSER="internet explorer"
cache:
  directories:
    - node_modules
before_script:
- node src/run.js &
- sleep 3
script:
- sleep 3
- if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then heroku local:run node_modules/.bin/mocha; fi
- if [ "$TRAVIS_PULL_REQUEST" = "true" ]; then heroku local:run node_modules/.bin/mocha --grep modules --invert; fi
#addons:
#  sauce_connect: true
#- mocha --harmony
addons:
  chrome: stable
services:
  - xvfb
before_install:
- . $HOME/.nvm/nvm.sh
- nvm install stable
- nvm use stable
- npm install -g heroku-cli
- npm install -g chromedriver
- export CHROME_BIN=chromium-browser
- export PATH=$PATH:node_modules/.bin/
before_deploy:
- export GIT_REV=`echo $TRAVIS_COMMIT`
- export GIT_BRANCH=`echo $TRAVIS_BRANCH`
- heroku config:set --app pyret-horizon GIT_REV=$GIT_REV
- heroku config:set --app pyret-horizon GIT_BRANCH=$GIT_REV
install:
- npm ci --ignore-scripts
- npm update # to update Pyret to the newest version
- make web
- make deploy-cpo-main
deploy:
  - provider: s3
    access_key_id: AKIAIFY44WM3LGA4OQSQ
    secret_access_key:
      secure: X50U/xTxW1OOBL5rQ6k764xAitKS77+NZfzAGgOKbk/0REUJEg3BHCYCqhr6/AtThh42HKBNNuG029Xu/0wQYOJq9JNWms61g25/1ig6HbeeaJbbpRLdRDWp59UAeB8tUQmPgI34DxREe2zcJJpNErepbkQ0XXx2tULF3HWBLD7PPOv4Ylb78bfhteIGKNX8+Ipag0gCGmJiTr9OPp6FCQh7kWzG1DBfT8t6gZJM9rhvE1y0Myv1OmcT2zs5ZCvd/uJWz7iiGjs4VvOJVTTFYs733B1NX3Inv3vlbgNny46JT7vT5M0RMgulb8ypkkzLham43yuQyn3eIGKVLd3AcTUtdNTB1TP4be50wT/FAoj195Ec1JAsO9LCKz79JPbUvoxdh9C+k+H0B0SHbL+VXqIhZGWLYq0GE/LZfBESYKAeNq/WfoNtfFXIv1VO0rgbX2FU/jxoM7uROagDhfeLBdmYhQVj3O4rXpcUDHcebBEycXlmC5zOaqmANZ37Pc3QIoR1is2+hkNzeP1/NV4huYOmJFlrD7dADKXIsh6vSyp6uZ49tabMfqSe9oKbl41Yc+uHEBm2vPXUF9vmm0SLOZScjFNyvd04EOXxTCBCww+qlFeIeHTyw9NgEIsOgUWUX44ZNZJATLnxCE9EZ+Sp5MHGDH7Wz5ceR5tZh68P7kw=
    bucket: 'pyret-horizon'
    local-dir: build/web/js
    upload-dir: new-horizons
    acl: public_read
    skip_cleanup: true
    detect_encoding: true
    on:
      repo: brownplt/code.pyret.org
      branch: horizon
  - provider: heroku
    app: pyret-horizon
    api_key:
      secure: "bYCQBcp2ai3oCR5B5YGGl6jpgesj7eTIJHzqotOdDKbqnOO0BRrVUEilKL8dpmpHba6UlqA1b4ACA6YAOxrTKmKM465gTdHHRWRdZqEahOQfN+i6TtViunG9OOa96zHFY4viqSsevdgZuC1Mec3IjvBS7TUhDPaozoPcrDWDGVVEa71+cUYWFpArRIboYcV+C7RXtnAHlBbeFqN6kIKBzPMb+O7NAykLaAikYrf9iVhTvb709Gnesh50y3CMexfdGhePi2xNRZDd7FU/5ZIbBPgGvZQ58DbXBoE5Ihd8rz915TojYpAQwbPLKdGvJ/Bvh44cZyPEEE5hUU45wXJUGUFHnZPIoTrKPk31LqfzkwfIolY4Rebbi9LZNY1j8Av42l+Xj2D2kWNtz06CKX2gxS4Ddk4xvz0jIMm1Co8Rv/J7vTP1IMNDBCGWH9osNahAR2PAW8JNWnmI2KroZvcK6k6SWD2c3S/Lakq/rfg12AaAucdlp6S4NsHe1zCowrd1uimYp3XNJWpgC0BTUtYVVK1OAuBgiMXknYpeXJXjFoxEp6uzJK5FwqJNwRK3o+5S3d2YJcKQMcAPhjGz94E2G3BZJtcBl2jGy7I9wKrjlqMG3gh6uXNbbiakk7epxwMmLnrjYQdaTJadtHRstM/tNoZKDNbIIMbWAgJBODWIU5k="
    on:
      repo: brownplt/code.pyret.org
      branch: horizon
