language: node_js
env:
  global:
  - TEST_LOC="sauce"
  - GOOGLE_CLIENT_ID=""
  - GOOGLE_CLIENT_SECRET=""
  - GOOGLE_API_KEY=""
  - REDISCLOUD_URL=""
  - BASE_URL=http://localhost:5000
  - SESSION_SECRET=not-so-secret-for-testing
  - USE_STANDALONE_PYRET=true
  - PYRET_RELEASE_BASE="https://s3.amazonaws.com/pyret-horizon/current"
  - PYRET="http://localhost:5000/js/cpo-main.jarr"
  - CURRENT_PYRET_RELEASE=""
  - PORT=5000
  - SAUCE_TEST_TARGET="http://localhost:5000"
  - SAUCE_USERNAME="pyret-lang"
  - secure: "E19TyEFE1iQSRrZI4w6ahWgFGEFZBiUgxn/Pqq5sQwHlMNpai+bVydDRVlcQ0NsrdPmyXY/4+29wMjsAHbSaiBuqgG5PbtpChJK7a+8583G6CrbkWdZgwkMDpqPQ2IBEWVYeybvl36wuXJ4HNCqImPODWvX1Wxzk5RCK/gM4PNu3OdmQm3+6O8y1N6r0Y/lnqeAxhaZ5wv01/6EE3I3rAbnFxnu0wIJ7AfNV64VRk+tqwYuM5fLXrl6yhelSwp9q5CLEwvvYknBkklHAXbvxc2qo8XfZb6Zb701NyGvFW86Acgo1dytqV+BNmxNj4FfnXj+rxi/SDpiKEifzj5UYLIAgAx/qbxWSHD8SHiOL1WMa7N3vN2Dh+O+9vCLDwtpzbC0kJqxVMei8buAR4pLReZO0OsmHGXDPApoqOdxvQ0Z2VtEWojIWaJSIl0gTaWKAPAE6GMT0zRQcmm6GPXmLpWGc/9MZKJ5lTXQloucRaStRhPYV4x2HNF4vVZmJ0RWQexAX4qsUiaVFs0jdnJTDvgyPWj+f7qJaaqNFfXz9TyP2N8LSjPdGBYfkWIbkv8dXjJCufXX29BbOD5Yq1NcRQxgTnQO1cvXs1/MJOrK8tCAQ/rZUqQakBMg71fhznOm2lejiiingfnq846C1v27KxZzFLnGIOfDUbMAgS1sbGUU="
  - secure: e0vpQGmW0d69Ql72Mw6gsGsMxAKgt61ZNqsfQEtNlAGtx7CbTKe3xg8kF1ygwFVEB7GDmTaojTcSGbRwqqZ5GAa8dsTAkefhOtfCDV5KUjvXXbpo9J/8YLiZiIy7ksHyh1yhByvvWmZZpjmdxWwcH8gUqtpae3bGtz7rQX3jLf2v3OR5uVFt8vKRMSR9imCWmq6tpnu+GVoaCFOHjq3U7LS1h78R2LJz+MnTuCbDtYFlxp/sAyS7vSXssFScl6wqOsgH5PHlj+kaHhFWLhzsAzG1RoHftqqIeinXzDcYo8EC/c6O3hMf2KtHm/Hsh1dPR8GnE6WClxPw0xNbh10jVf7b1CXuzKGF8a1JlmtsVztiujsMswZGGLpTkqBvBAiuDsMOwKFNk7UrR5FA/0bVMMsluKxW/0UBzVPN9QyMKAs19ca1t/qT3abxYFyvXrDibKMLuS1uCCsZbwTkjkPwfWBzin8ohK2gLi+y24eQFSd27XWcmk+fJHfgJ458OgvczubK0CsyPAaJtCvRBYKvLQaEtkc4RkoM0yx6NhYYLCZqH1DRneam40rVSrVO41yT/PUnA5U64q16ptbn90Vgw/yKlp9OLtWKheBDTinwbst1kegbCSj4qZtORFLIQIUsZQN6SUm9tCACqFosDpRXAzURc2IOdsSUmtJEqvkijsc=
node_js:
- 6.2.1
before_install:
- gem install heroku
before_script:
- node src/run.js &
- sleep 3
addons:
  sauce_connect: true
install:
- npm install --ignore-scripts
- make web
- make deploy-cpo-main
before_deploy:
- heroku config:set --app patch-experiment PYRET=https://d251z2akfyabv3.cloudfront.net/releases/$TRAVIS_COMMIT/cpo-main.jarr.gz
deploy:
- provider: s3
  access_key_id: AKIAJI5QOXMOMALYEG3Q
  secret_access_key:
    secure: eNHYX/jlPW4ZWOhl3q2XzXaEG0RF3LyNmJ2VULnAocCKfgcSLvrAJalzXZ7wyK7WOBPN9liaLaams0Vq0WqabS09F7TQQYQG0yHx5L2bxkiUmJmMlpku0/Her1/6j+QH7YlLHjHmHF4HNJUgEpp/mwDF4x4/NdQ9H8wGdJSw3OwkE7+27Xg/5OmgKkDOJR/6d9y5Ha8PvVeEt1XC4OMtEn+Himao/X8GUVtrCmnyaACoyuIAS0aYkD5YdpXoluNJW3Iv/aqZOic5zrxx0XCfAneD/bQfCI0LneOICOjLxWkHttjFVTLfzJr4cCB1mFfAAh6fh0BipTVQZze3qp02ziKDJgYPD/Lo6pyuyG+ENwCS/s0jOywpTT4L0MdGUC50eNrrRFpQ5Fch6e2zvdWoj9/eB42VDijP8d+nguwRm/gt/z/6vo4jZaVGdlZaUr4Bx1ejX/30aiw+ezQjPoD2A7tAH7A9qygVAPmvJ7kvYOf+jLzhQUxkQna4lx2BdpirhX/QT8GLoei6LuZ/MQmy79jmlQnR7PUpeVwuN4DK0X5W/0774wPcFhETvr7IpF5DWdZlb8wqg8440abhD2sYBYqpmv9FehdEBSgyFvA2uxIZ7AcBICv47Lz9cvB6rjN1cjAUWRaSB9q54ej18l8o68OZUXe1TY5ek3c+Go2V88k=
  bucket: pyret-releases
  local-dir: build/release
  upload-dir: releases
  acl: public_read
  skip_cleanup: true
  detect_encoding: true
  on:
    repo: brownplt/code.pyret.org
    branch: release
- provider: heroku
  app: patch-experiment
  api_key:
    secure: h516V/Ze+mXMWSinCVzpwuRBsdx3nNbo7iEsWovrdIoVwz01tEQnwaTsGMviOq7P/X5bu+PuOAD0Kpm3lfds0/ctaB4y/O5zKvba1A4jdHSjvgADRvgbx1FxoArkwnuI1s9/TFfTXdN7zFDbJWFiXy3g0o7xp5X22Q21ZgrjGLv0fNBbxRvIm441lQgn13uZD45+uS12jSDMJ7DZU7vBoSnq1DACWHNuWORb/PRZnDPpwjKUwX9BEYaYmkoupB2WpgcSTlglVnDpFHnaOmUO/yeJHlsuFe4E4BMRrjccsSB2ZGdj05YtR4pg2biQSJmXMe8+OfBpteH8MF4LYH4mIEsA56xDR47IYGaGDo7oxIaS6gWE7u+w2UkMO5/Tv4W+V9hHEoAA9stX52x8jHDUe8qcYs/Gb/GWYLQFkolr8dczrBF/kojUELm7KztlOWmPCxW6kTd3M4imWO0bbHEHgDDlxLbhBgYLkh+Jw3BSwaDeWx2G00Xy/cZ2XELN1s5cnQ+g7A2/YjaRos2hX59HCFALgx8FoMzXCmnUXZX5hqUloMjY1a/zomw+fa5WEOYF41TRQmkdqwmwj9WiW160jXtOJbdKTncdw9BXc9OULDjGg4FbPPMCT/zva3AsMYoWbGJdLLEhQPyUsf1gzPz7ToZ5E8ykxWpopNDQg7i2mKY=
  on:
    repo: brownplt/code.pyret.org
    branch: release
